/** SSOT for Introduction page (`article_type: home`, slug `home`) body when DB is unavailable. */

const HOME_MERMAID = [
  "flowchart TB",
  '    subgraph L1["① User layer"]',
  "        direction LR",
  '        U[User] --> CMD["Slash command<br/>verb · object · domain · intent"]',
  "    end",
  "",
  '    subgraph L2["② Control layer"]',
  "        direction RL",
  '        DISP[Dispatch] --> POL[Policies] --> ONT[Ontology] --> GRA["Execution graph"]',
  "    end",
  "",
  '    subgraph L3["③ Run layer"]',
  "        direction LR",
  '        RUN["Create Run"] --> PEND["Queue pending phases<br/>lifecycle + gate stack"] --> HK["Runtime hooks<br/>block edits until execute"] --> OBS["Observability on Run<br/>decisions · log · artifacts · checkpoints"]',
  "    end",
  "",
  '    subgraph L4["④ Execution layer"]',
  "        direction RL",
  '        ORCH[Orchestrator] --> CAP[Capabilities] --> SK["Skills and agents"]',
  "    end",
  "",
  '    subgraph L5["⑤ Work lifecycle"]',
  "        direction LR",
  '        DISC[Discover] --> INV["Investigate<br/>lite or swarm"] --> RC["Root cause<br/>fix verb"] --> PLAN[Plan]',
  "    end",
  "",
  '    subgraph L6["⑥ Governance gates"]',
  "        direction RL",
  "        VAL[Validate] --> IMP[Impact analysis] --> DEP[Dependency graph] --> FIT[Fitness functions] --> RB[Rollback]",
  "    end",
  "",
  '    subgraph L7["⑦ Delivery"]',
  "        direction LR",
  '        EX[Execute] --> VER[Verify] --> REP[Report] --> DONE["Run completed"]',
  "    end",
  "",
  '    STOP["Stop — awaiting approval"]',
  "",
  "    CMD --> DISP",
  "    GRA --> RUN",
  "    OBS --> ORCH",
  "    SK --> DISC",
  "    PLAN --> VAL",
  "    RB -->|pass| EX",
  "    RB -->|fail| STOP",
  "    STOP -->|user approves| VAL",
].join("\n");

export const HOME_INTRO_CONTENT = [
  "## Welcome to Lüdecker",
  "",
  "This site is about Agentic OS—also called Agentic Architecture as Code (AAAC). You run slash commands; the repo owns the workflow; every chat leaves a reviewable trail.",
  "",
  "If you build with Cursor on a shared codebase, start here. Install the generic kernel on any project with the [Install AAAC guide](https://ludecker.com/guide/install-aaac). For the full story, read [Introducing Agentic OS](https://ludecker.com/articles/agentic-os).",
  "",
  "## How Agentic OS flows in one picture",
  "",
  "Follow the numbered layers top to bottom. Odd layers flow left → right; even layers flow right → left — a compact snake layout. The Run is created early (layer ③) and updated after every phase. Governance gates (⑥) sit after plan and before execute; a failed gate stops for human approval.",
  "",
  "```mermaid",
  HOME_MERMAID,
  "```",
  "",
  "**Legend:** ① what you type · ② repo resolves command and routing · ③ Run manifest owns state for the whole chat · ④ who does the work · ⑤ research and planning phases · ⑥ approval checkpoints (not work) · ⑦ code changes, verification, and completion.",
  "",
  'You type `/verb-object domain "intent"` (and flags when needed). Everything after intent is architecture in the repo—not something you improvise in chat.',
  "",
  "## What you will find here",
  "",
  "Essays, guides, skills, tools, and diagrams for people who ship with agents. Pick a section in the sidebar, install AAAC on your own repo with the [install guide](https://ludecker.com/guide/install-aaac), or continue with [Introducing Agentic OS](https://ludecker.com/articles/agentic-os).",
].join("\n");
